## Vivado Project Script (Reference Only)

This repository includes a `create_project.tcl` file generated by
**Vivado 2024.1**.

Purpose of this script:

- Documents the original Vivado project setup
- Shows how the RTL was integrated with:
  - Zynq UltraScale+ MPSoC (KV260)
  - AXI DMA
  - AXI-Lite control path
- Serves as a reproducibility reference

Important notes:

- This script is **not intended as a portable build system**
- Board-specific settings (KV260, PS configuration, memory map) are hard-coded
- Users are **not expected to run this script**
- RTL files (`rms_peak_core.v`, `rms_peak_axis.v`) are fully standalone and can be reused independently

The repository focuses on **RTL design and verification**, not on providing a complete Vivado project.
